[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SpatialGlue"
authors = [{name = "Yahui Long", email = "longyh@immunol.a-star.edu.sg"}]
dynamic = ["version", "description"]
